version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:15beta2-alpine3.16
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${PGPASSWORD:-root}
      POSTGRES_USER: ${PGUSER:-root}
      POSTGRES_DB: ${PGDATABASE:-service}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.11
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: sample@gmail.com
      PGADMIN_DEFAULT_PASSWORD: rooted

